- hosts: 192.168.50.127
  gather_facts: no
  tasks:
  - name: Deploy service heatmap
    k8s:
      state: present
      validate_certs: no
      namespace: production-dev
      kubeconfig: '/home/jenkins/.kube/config'
      definition:
        # heatmap-deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: heatmap-service
          namespace: staging-ai
          env: staging
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: heatmap-service
          template:
            metadata:
              labels:
                app: heatmap-service
                tier: ai
            spec:
              nodeSelector:
                beta.kubernetes.io/os: linux
                kubernetes.io/arch: amd64
                env: staging
              containers:
                - name: service-container
                  image: "{{ image }}"
                  ports:
                    - containerPort: 5017
                  envFrom:
                  - configMapRef:
                      name: heatmapservice-env-configmap
                  imagePullPolicy: Always
              imagePullSecrets:
              - name: dockerhub

